# -*- mode: python ; coding: utf-8 -*-

import os

from PyInstaller.utils.hooks import collect_all

_q_datas, _q_binaries, _q_hidden = collect_all('questionary')
_pt_datas, _pt_binaries, _pt_hidden = collect_all('prompt_toolkit')
_wc_datas, _wc_binaries, _wc_hidden = collect_all('wcwidth')

# Auto-update stack (tufup + TUF + securesystemslib + certifi CA bundle).
# These pull native crypto and data files (e.g. certifi/cacert.pem) that must
# be bundled for update verification to work in the frozen exe.
_upd_datas, _upd_binaries, _upd_hidden = [], [], []
for _pkg in ('tufup', 'tuf', 'securesystemslib', 'certifi'):
    _d, _b, _h = collect_all(_pkg)
    _upd_datas += _d
    _upd_binaries += _b
    _upd_hidden += _h

# Trust anchor for signed updates. Generated by packaging/repo_init.py; it is
# public, so it is committed and bundled at the exe root (sys._MEIPASS). The
# build still works without it (e.g. before the repo is initialised), but
# auto-update is then inert until a root.json ships.
_root_json = os.path.join('packaging', 'trusted', 'root.json')
if os.path.exists(_root_json):
    _upd_datas.append((_root_json, '.'))
elif os.environ.get('LMU_EP_REQUIRE_UPDATE_ANCHOR'):
    # Release builds set this so a missing anchor is a hard error rather than a
    # silently updater-disabled exe.
    raise SystemExit(
        f"ERROR: {_root_json} missing but LMU_EP_REQUIRE_UPDATE_ANCHOR is set. "
        "Run packaging/repo_init.py to generate the update trust anchor before "
        "building a release.")
else:
    print(f"WARNING: {_root_json} missing; building without an update trust "
          "anchor (auto-update will be disabled in this build). Set "
          "LMU_EP_REQUIRE_UPDATE_ANCHOR=1 to make this an error for releases.")

# The GUI only uses QtCore, QtGui and QtWidgets. Collecting the whole of
# PySide6 bundled Qt WebEngine alone at ~290 MB (Qt6WebEngineCore.dll plus
# its .pak/ICU resources), as well as QtQuick/QML, Qt3D, QtMultimedia,
# QtPdf, etc. — none of which we use.
# Declaring just the three modules as hidden imports lets PyInstaller's
# per-module PySide6 hooks collect only what they need. They must be hidden
# imports because the actual imports are lazy (inside functions in gui.py /
# splash.py) and so are invisible to static analysis.
_qt_hidden = ['PySide6.QtCore', 'PySide6.QtGui', 'PySide6.QtWidgets']

# Belt-and-suspenders: keep the heavy, unused Qt feature modules from being
# transitively pulled back in.
_qt_excludes = [
    'PySide6.QtWebEngineCore',
    'PySide6.QtWebEngineWidgets',
    'PySide6.QtWebEngineQuick',
    'PySide6.QtWebChannel',
    'PySide6.QtWebSockets',
    'PySide6.QtWebView',
    'PySide6.QtQml',
    'PySide6.QtQuick',
    'PySide6.QtQuick3D',
    'PySide6.QtQuickControls2',
    'PySide6.QtQuickWidgets',
    'PySide6.Qt3DCore',
    'PySide6.Qt3DRender',
    'PySide6.Qt3DExtras',
    'PySide6.QtMultimedia',
    'PySide6.QtMultimediaWidgets',
    'PySide6.QtPdf',
    'PySide6.QtPdfWidgets',
    'PySide6.QtCharts',
    'PySide6.QtDataVisualization',
    'PySide6.QtGraphs',
    'PySide6.QtDesigner',
    'PySide6.QtLocation',
    'PySide6.QtPositioning',
    'PySide6.QtSql',
    'PySide6.QtTest',
    'PySide6.QtSensors',
    'PySide6.QtSerialPort',
    'PySide6.QtSerialBus',
    'PySide6.QtBluetooth',
    'PySide6.QtNfc',
    'PySide6.QtRemoteObjects',
    'PySide6.QtScxml',
    'PySide6.QtStateMachine',
    'PySide6.QtTextToSpeech',
    'PySide6.QtVirtualKeyboard',
    'PySide6.QtHelp',
    'PySide6.QtNetworkAuth',
    'PySide6.QtSpatialAudio',
]

a = Analysis(
    ['src/lmu_ep_client/cli.py'],
    pathex=['src', 'vendor'],
    binaries=_q_binaries + _pt_binaries + _wc_binaries + _upd_binaries,
    datas=_q_datas + _pt_datas + _wc_datas + _upd_datas,
    hiddenimports=_q_hidden + _pt_hidden + _wc_hidden + _qt_hidden + _upd_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=_qt_excludes,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='lmu-ep-client',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    # Windowed: double-click shows the splash + GUI with no black console.
    # CLI invocation reattaches to the parent terminal via AttachConsole at
    # startup (see stdio_setup.attach_parent_console).
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
